In [55]:
import numpy as np
import random
from scipy import stats

from sklearn.datasets import make_blobs

In [56]:
X, y = make_blobs(n_samples=100, centers=2, n_features=2,random_state=0)

In [57]:
m, n = np.shape(X)
m, n

X = np.c_[ np.ones(m), X]

print(X[:5])
print(y[:5])

[[ 1.          4.21850347  2.23419161]
 [ 1.          0.90779887  0.45984362]
 [ 1.         -0.27652528  5.08127768]
 [ 1.          0.08848433  2.32299086]
 [ 1.          3.24329731  1.21460627]]
[1 1 0 0 1]


In [63]:
m, n = x.shape
m, n 

(100, 3)

In [59]:
def cross_entriy(true_label, predicted):
  if true_label == 1:
    return -1*np.log(predicted)
  else:
    return -1*np.log(1 - predicted)

In [67]:
def gradient_descent_3(alpha, x, y, numIterations):
    """
    Функция реализует алгоритм градиентного спуска. На каждом шаге выводится значение функции потерь
    """
    
    m, n = x.shape # размерности признакового пространства
    theta = np.ones(n) # ВЕСА МОДЕЛИ!!!
    x_transpose = x.transpose() # транспонированная матрица x
    
    for iter in range( 0, numIterations ):
        hypothesis = np.dot(x, theta) # матричное произведение
        a = 1/(1+np.exp(-1*hypothesis))
        l = a - y
        LL = np.sum(list(map(cross_entriy,y,a)))  # функция потерь
        print( "iter %s | J: %.3f" % (iter, LL) )
        G = np.dot(x_transpose, l) / m
        theta = theta - alpha * G  # update
    return theta

In [86]:
%%time
# шаг алгоритма
alpha = 5
theta = gradient_descent_3(alpha, X, y, 500)

iter 0 | J: 316.889
iter 1 | J: 752.999
iter 2 | J: 147.475
iter 3 | J: 39.115
iter 4 | J: 33.733
iter 5 | J: 32.489
iter 6 | J: 31.271
iter 7 | J: 30.076
iter 8 | J: 28.905
iter 9 | J: 27.758
iter 10 | J: 26.637
iter 11 | J: 25.545
iter 12 | J: 24.482
iter 13 | J: 23.450
iter 14 | J: 22.453
iter 15 | J: 21.491
iter 16 | J: 20.569
iter 17 | J: 19.689
iter 18 | J: 18.854
iter 19 | J: 18.066
iter 20 | J: 17.329
iter 21 | J: 16.647
iter 22 | J: 16.020
iter 23 | J: 15.451
iter 24 | J: 14.942
iter 25 | J: 14.491
iter 26 | J: 14.099
iter 27 | J: 13.761
iter 28 | J: 13.475
iter 29 | J: 13.235
iter 30 | J: 13.035
iter 31 | J: 12.870
iter 32 | J: 12.733
iter 33 | J: 12.619
iter 34 | J: 12.523
iter 35 | J: 12.440
iter 36 | J: 12.367
iter 37 | J: 12.302
iter 38 | J: 12.243
iter 39 | J: 12.189
iter 40 | J: 12.138
iter 41 | J: 12.089
iter 42 | J: 12.043
iter 43 | J: 11.999
iter 44 | J: 11.957
iter 45 | J: 11.916
iter 46 | J: 11.876
iter 47 | J: 11.837
iter 48 | J: 11.800
iter 49 | J: 11.764
iter 50