In [1]:
import numpy as np

In [28]:
# Создаем матрицу 3 на 3, заполненную числами от 1 до 9

m = np.arange(1,10).reshape((3, 3))
print (m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
# Прибавляем к ней матрицу с единицами на диагонале

I = np.eye(3)
print ('Единичная матрица')
print (I)
mI = m+I
print ('Сложение мартицы с единичной матрицой')
print (mI)

Единичная матрица
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Сложение мартицы с единичной матрицой
[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]


In [30]:
# Умножаем полученную матрицу на вектор (1, 2, 3)

v1 = np.array([1,2,3])
print(v1)
print('Умножение вектора на матрицу')
vmI = mI * v1
print(vmI)

[1 2 3]
Умножение вектора на матрицу
[[ 2.  4.  9.]
 [ 4. 12. 18.]
 [ 7. 16. 30.]]


In [31]:
# Считаем обратную матрицу к полученной матрице

vmI_inv = np.linalg.inv(vmI)
print('Обратная матрица')
print(vmI_inv)
print('Проверка. Должна получиться единичная матрица')
print(np.dot(vmI_inv,vmI))

Обратная матрица
[[-6.         -2.          3.        ]
 [-0.5         0.25        0.        ]
 [ 1.66666667  0.33333333 -0.66666667]]
Проверка. Должна получиться единичная матрица
[[ 1.00000000e+00 -7.10542736e-15 -1.42108547e-14]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
