In [5]:
import matplotlib.pyplot as plt
import numpy as np

from scipy.optimize import minimize
%matplotlib inline

In [6]:
# строки - пользователи (10 человек), столбцы - фильмы (15 фильмов)
raitings = np.array([[ 4,  4,  9,  4,  1,  6, 10,  7,  9,  6,  9,  2,  8,  6,  6],
                     [ 9,  2,  5, 10,  7,  8, 10,  5,  6,  2,  1,  6,  8,  9,  7],
                     [ 1,  6,  8,  8,  4,  9,  3,  8, 10,  5,  2,  6,  8,  1,  6],
                     [ 6,  1,  9,  7,  7,  9,  2,  3,  5,  1,  6,  6,  3,  2,  7],
                     [ 3,  7,  3,  5,  7,  9,  9,  6,  2,  9,  1,  2,  8, 10,  6],
                     [ 8,  3,  7,  3,  8,  6,  1,  8,  8,  6,  1,  9,  4, 10,  1],
                     [ 9,  8,  4,  8,  8, 10,  6,  1,  1,  2,  9,  5,  2,  7,  2],
                     [ 4,  1,  6,  4,  3, 10,  4,  4,  2,  8,  7,  9,  3,  8,  3],
                     [ 2,  7,  7,  6, 10,  6,  8,  9,  8,  6, 10,  1,  7, 10,  4],
                     [ 5, 10,  8,  8,  9,  7,  2,  9,  9, 10,  8,  8,  8,  6, 10]])
print (raitings)

[[ 4  4  9  4  1  6 10  7  9  6  9  2  8  6  6]
 [ 9  2  5 10  7  8 10  5  6  2  1  6  8  9  7]
 [ 1  6  8  8  4  9  3  8 10  5  2  6  8  1  6]
 [ 6  1  9  7  7  9  2  3  5  1  6  6  3  2  7]
 [ 3  7  3  5  7  9  9  6  2  9  1  2  8 10  6]
 [ 8  3  7  3  8  6  1  8  8  6  1  9  4 10  1]
 [ 9  8  4  8  8 10  6  1  1  2  9  5  2  7  2]
 [ 4  1  6  4  3 10  4  4  2  8  7  9  3  8  3]
 [ 2  7  7  6 10  6  8  9  8  6 10  1  7 10  4]
 [ 5 10  8  8  9  7  2  9  9 10  8  8  8  6 10]]


In [25]:
arr_similar_users=[]
arr_lenght = np.linalg.norm(raitings, axis = 1)
arr_cos_measure = np.zeros((10, 10))
for inc1, row1 in enumerate(raitings):
    min_cos_measure = 100
    curr_user,len_curr_user = inc1,arr_lenght[inc1]
    for inc2, row2 in enumerate(raitings):
        ind_user,len_user,scalar = inc2,arr_lenght[inc2],np.dot(row1,row2)
        if inc1!=inc2:
            curr_cos_measure = round(np.degrees(np.arccos(scalar/(len_curr_user*len_user))),2)
            if curr_cos_measure < min_cos_measure:
                min_cos_measure = curr_cos_measure
                similar_user,len_similar_user,dot_scalar = ind_user,len_user,scalar
        else:
            curr_cos_measure = 100
        arr_cos_measure[inc1,inc2] = curr_cos_measure
            
    dc = dict.fromkeys(['curr_user','similar_user','min_cos_measure','len_curr_user','len_similar_user','dot_scalar'])
    dc['curr_user']=curr_user+1
    dc['similar_user']=similar_user+1
    dc['min_cos_measure']=min_cos_measure
    dc['len_curr_user']=len_curr_user
    dc['len_similar_user']=len_similar_user
    dc['dot_scalar']=dot_scalar
    arr_similar_users.append(dc)

print (arr_cos_measure)
# print (arr_similar_users)

[[100.    34.31  31.87  38.43  35.    42.17  43.33  35.94  24.4   30.67]
 [ 34.31 100.    35.67  32.18  29.38  34.19  34.28  36.85  34.38  34.95]
 [ 31.87  35.67 100.    32.15  38.38  37.72  47.46  40.28  34.8   23.26]
 [ 38.43  32.18  32.15 100.    46.25  38.13  33.62  33.97  39.01  30.81]
 [ 35.    29.38  38.38  46.25 100.    39.06  38.56  35.67  28.42  32.25]
 [ 42.17  34.19  37.72  38.13  39.06 100.    42.26  32.38  36.27  31.22]
 [ 43.33  34.28  47.46  33.62  38.56  42.26 100.    34.24  35.78  37.67]
 [ 35.94  36.85  40.28  33.97  35.67  32.38  34.24 100.    37.05  33.19]
 [ 24.4   34.38  34.8   39.01  28.42  36.27  35.78  37.05 100.    25.72]
 [ 30.67  34.95  23.26  30.81  32.25  31.22  37.67  33.19  25.72 100.  ]]


In [26]:
arr_similar_users



[{'curr_user': 1,
  'similar_user': 9,
  'min_cos_measure': 24.4,
  'len_curr_user': 25.553864678361276,
  'len_similar_user': 28.0178514522438,
  'dot_scalar': 652},
 {'curr_user': 2,
  'similar_user': 5,
  'min_cos_measure': 29.38,
  'len_curr_user': 26.814175355583846,
  'len_similar_user': 25.079872407968907,
  'dot_scalar': 586},
 {'curr_user': 3,
  'similar_user': 10,
  'min_cos_measure': 23.26,
  'len_curr_user': 24.515301344262525,
  'len_similar_user': 31.25699921617557,
  'dot_scalar': 704},
 {'curr_user': 4,
  'similar_user': 10,
  'min_cos_measure': 30.81,
  'len_curr_user': 21.6794833886788,
  'len_similar_user': 31.25699921617557,
  'dot_scalar': 582},
 {'curr_user': 5,
  'similar_user': 9,
  'min_cos_measure': 28.42,
  'len_curr_user': 25.079872407968907,
  'len_similar_user': 28.0178514522438,
  'dot_scalar': 618},
 {'curr_user': 6,
  'similar_user': 10,
  'min_cos_measure': 31.22,
  'len_curr_user': 24.392621835300936,
  'len_similar_user': 31.25699921617557,
  'dot_sc