In [5]:
import numpy as np
from pylab import *
from scipy.optimize import *
#x = fromfile(’x.dat’,float,sep=’\n’)
#y = fromfile(’y.dat’,float,sep=’\n’)
#def f(t,Omega,tau):
#return exp(-t/tau)*sin(Omega*t)
#def delta(p):
#Omega,tau = p
#return y-f(x,Omega,tau)
#Omega,tau = leastsq(delta,(1,10))[0]




In [44]:
def f(x, a, b):
    return np.e**a * np.sin(b*x) + x

def error(params):
    return np.sum(np.abs(fx - f(x, params[0], params[1])))

def error1(params):
    return np.abs(fx - f(x, params[0], params[1]))


x = np.array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
              1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
              2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
              3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

fx = np.array([  0.        , -12.01819092, -18.90968634, -17.68786571,
                -8.7529108 ,   4.27524517,  16.06801336,  21.81250213,
                19.22059845,   9.48411207,  -3.22273056, -13.48576488,
               -16.91096359, -11.95866834,  -0.58630088,  12.56873816,
                22.12489421,  24.20292139,  18.04522521,   6.33211092])


In [41]:
x0 = np.array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
              1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
              2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
              3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

fx = np.array([  0.        , -12.01819092, -18.90968634, -17.68786571,
                -8.7529108 ,   4.27524517,  16.06801336,  21.81250213,
                19.22059845,   9.48411207,  -3.22273056, -13.48576488,
               -16.91096359, -11.95866834,  -0.58630088,  12.56873816,
                22.12489421,  24.20292139,  18.04522521,   6.33211092])


x = x0
y = fx
def f(t,Omega,tau):
    return exp(-t/tau)*sin(Omega*t)
def delta(p):
    Omega,tau = p
    return y-f(x,Omega,tau)

#Omega,tau = leastsq(delta,(1,10))[0]
print(leastsq(delta,(1,10)))

(array([   0.34905616, -287.10615397]), 5)


In [42]:
p = (1,10)
delta(p)

array([  0.        , -12.27156567, -19.38628169, -18.34395262,
        -9.53484358,   3.42688654,  15.21410206,  21.01116648,
        18.52342504,   8.93298671,  -3.5979628 , -13.66870406,
       -16.89907642, -11.76274892,  -0.22905614,  13.05483737,
        22.70031327,  24.82410216,  18.66774291,   6.91372789])

In [45]:
params = (1,10)
error1(params)

array([ 0.        , 13.60838478, 17.11969339, 21.19336402,  7.38109631,
        1.4436689 , 14.71038905, 21.0998699 , 14.92254479,  9.81368052,
        8.37079392, 14.68602909, 20.5100348 , 16.30413105,  2.21579989,
        5.95933076, 20.50618049, 17.86733048, 13.96648346,  2.04531972])

In [47]:
#a, b = leastsq(error,(1,10))[0]
#np.sum(np.abs(fx - f(x, 1, 10)))
#p1, success = leastsq(error,[1,1])
p0 = np.array([1.0,1.0])
p1, success = leastsq(error1, p0)

print(p1)
print(success)

[1.29675048 3.38240834]
1


In [49]:
from scipy.optimize import minimize
x0 = np.array([10.0,1.0])
res = minimize(error, x0)

print(res)

      fun: 244.29483415256246
 hess_inv: array([[3.23340895e+00, 1.66057356e-09],
       [1.66057356e-09, 5.85308908e-11]])
      jac: array([-0.21471596,  2.21123314])
  message: 'Desired error not necessarily achieved due to precision loss.'
     nfev: 607
      nit: 35
     njev: 149
   status: 2
  success: False
        x: array([1.52248862, 4.58904321])


In [55]:
import numpy as np
from scipy.optimize import minimize
x0 = np.array([5.0,5.0])
res = minimize(error, x0, method='SLSQP')

print(res.x)

[2.28727685 5.00719406]


/home/evgen/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in double_scalars
  
/home/evgen/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in multiply
  
